version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: messenger_nginx
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - messenger_network

  app:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    image: messenger_app:latest
    container_name: messenger_app
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8080:8080"
    networks:
      - messenger_network

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: messenger_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - messenger_network

  mongo:
    image: mongo:latest
    container_name: messenger_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - messenger_network

volumes:
  mongo_data:

networks:
  messenger_network:
    driver: bridge